vendor dropdown component added
Accolite-Glasgow-Tech/TFR-Tracker-FrontEnd pull request #1
Opened 2022-12-21 00:23 UTC by rishali

2022-12-21 00:26 UTC, rishali commented
@sahuaccolite @prashantaccolite

2022-12-21 14:27 UTC, rishali commented
Vendor commit update

2022-12-21 14:28 UTC, prasadkorrapati requested changes

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/app.component.ts
> +  ngOnInit() {
This does not need here. the component who is using this  vendor component may do the implementation

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/app.component.html
> +      <app-vendors [vendors]="vendors" (onSelected)="onVendorSelected($event)"
This is not required here now. TFR details component will use this later

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/app.module.ts
> +        VendorsComponent    ],
declarations: [
        AppComponent,
        VendorsComponent
],

properly format this code above

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/core-modules/core-material/core-material.module.ts
> +const materialModules = [MatIconModule, MatButtonModule, MatSidenavModule, MatToolbarModule,
const materialModules = [
  MatIconModule,
  MatButtonModule,
  MatSidenavModule,
  MatToolbarModule,
  MatSelectModule,
  FlexLayoutModule,
];
Indent properly as above

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/core-modules/core-material/core-material.module.ts
> +  imports:  [BrowserModule, FormsModule, BrowserAnimationsModule,CommonModule,
imports: [
  BrowserModule,
  FormsModule,
  BrowserAnimationsModule,
  CommonModule,
  materialModules,
];
format code as above

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/core-modules/core-material/core-material.module.ts
> -    FlexLayoutModule,
exports: [
  BrowserModule,
  FormsModule,
  BrowserAnimationsModule,
  CommonModule,
  materialModules,
];

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/service/apiservice.service.ts
> +    console.log('Vendors ', this.Vendors);
you can remove this console.log

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/service/apiservice.service.ts
> +  getVendorData(): Observable<Vendor[]> {
looks good.

2022-12-21 14:28 UTC, prasadkorrapati commented on src/app/types/types.d.ts
> +export interface Vendor {
Looks good.

2022-12-21 14:28 UTC, prasadkorrapati commented on src/assets/json/vendors.json
> +[{
Looks good.

2022-12-21 14:28 UTC, rishali commented on src/app/app.component.html
>        </mat-sidenav>
testing

2022-12-21 14:59 UTC, prasadkorrapati commented on src/app/app.component.html
> +<div style="height: 100vh">
looks good

2022-12-21 15:34 UTC, prasadkorrapati approved these changes
Looks good.

2022-12-21 15:34 UTC, prasadkorrapati commented on src/app/components/vendors/vendors.component.html
> +<mat-form-field appearance="fill">
looks good

2022-12-21 15:34 UTC, prasadkorrapati commented on src/app/core-modules/core-material/core-material.module.ts
> +const materialModules = [
looks good

2022-12-21 15:34 UTC, prasadkorrapati commented on src/app/service/apiservice.service.ts
> +export class ApiserviceService {
Change the service name to ApiService

2022-12-28 10:10 UTC, rishali commented
@sahuaccolite

2022-12-28 10:14 UTC, sahuaccolite commented
Test

2023-01-10 09:02 UTC, sahuaccolite commented on src/app/components/charts/charts.service.ts
> +    this.readTfrStatusData().subscribe((data) => {});
Why this needed ? please remove this

2023-01-10 09:02 UTC, sahuaccolite commented on src/app/components/charts/charts.service.ts
> +  tfrStatus: IStatus[] = require('../../../assets/json/status.json');
As already  suggested we not need require here here we just need path and call get directly let me know if anything needs to be dicsussed

2023-01-10 18:08 UTC, sahuaccolite approved these changes

2023-01-11 09:59 UTC, angularavengers approved these changes

2023-01-11 10:20 UTC, sahuaccolite commented
Merged

2023-01-11 10:21 UTC, sahuaccolite commented
Merged

2023-01-11 10:22 UTC, sahuaccolite commented
Merged

2023-01-11 10:23 UTC, sahuaccolite commented
Merged

2023-01-11 10:26 UTC, sahuaccolite commented
Approved

2023-01-11 11:04 UTC, sahuaccolite approved these changes

2023-01-11 11:05 UTC, merged